# $FreeBSD$

PORTNAME=	mm5dread
PORTVERSION=	0.1
CATEGORIES=	net
MASTER_SITES=	http://www.szerafingomba.hu/softwares/mm5dread/

MAINTAINER=	pozsar.zsolt@szerafingomba.hu
COMMENT=	Environment characteristics editor

GNU_CONFIGURE=	yes

.include <bsd.port.mk>

CONFIGURE_ARGS+=stagedir=$(STAGEDIR)/$(PREFIX)
